// Schemas (runtime validation)
export {
    actionToken,
    baseMsg,
    challMsg,
    channel,
    device,
    devicePayload,
    emoji,
    errMsg,
    filePayload,
    fileResponse,
    fileSQL,
    identityKeys,
    invite,
    keyBundle,
    mailSQL,
    mailWS,
    notifyMsg,
    permission,
    preKeysSQL,
    preKeysWS,
    receiptMsg,
    registrationPayload,
    resourceMsg,
    respMsg,
    server,
    sessionSQL,
    MailType,
    SocketAuthErrors,
    storedCredentials,
    successMsg,
    TokenScopes,
    user,
    userRecord,
} from "./schemas/index.js";

// Types (zero-cost z.infer)
export type {
    IActionToken,
    IBaseMsg,
    IChallMsg,
    IChannel,
    IDevice,
    IDevicePayload,
    IEmoji,
    IErrMsg,
    IFilePayload,
    IFileResponse,
    IFileSQL,
    IIdentityKeys,
    IInvite,
    IKeyBundle,
    IMailSQL,
    IMailWS,
    INotifyMsg,
    IPermission,
    IPreKeysSQL,
    IPreKeysWS,
    IReceiptMsg,
    IRegistrationPayload,
    IResourceMsg,
    IRespMsg,
    IServer,
    ISessionSQL,
    ISuccessMsg,
    IUser,
    IUserRecord,
    KeyStore,
    StoredCredentials,
} from "./schemas/index.js";
