// Schemas (runtime validation)
export {
    actionToken,
    baseMsg,
    datetime,
    challMsg,
    channel,
    device,
    devicePayload,
    emoji,
    errMsg,
    filePayload,
    fileResponse,
    fileSQL,
    identityKeys,
    invite,
    keyBundle,
    mailSQL,
    MailType,
    mailWS,
    notifyMsg,
    permission,
    preKeysSQL,
    preKeysWS,
    receiptMsg,
    registrationPayload,
    resourceMsg,
    respMsg,
    server,
    sessionSQL,
    SocketAuthErrors,
    storedCredentials,
    successMsg,
    TokenScopes,
    user,
    userRecord,
} from "./schemas/index.js";

// Types (zero-cost z.infer)
export type {
    ActionToken,
    BaseMsg,
    ChallMsg,
    Channel,
    Device,
    DevicePayload,
    Emoji,
    ErrMsg,
    FilePayload,
    FileResponse,
    FileSQL,
    IdentityKeys,
    Invite,
    KeyBundle,
    MailSQL,
    MailWS,
    NotifyMsg,
    Permission,
    PreKeysSQL,
    PreKeysWS,
    ReceiptMsg,
    RegistrationPayload,
    ResourceMsg,
    RespMsg,
    Server,
    SessionSQL,
    SuccessMsg,
    User,
    UserRecord,
    KeyStore,
    StoredCredentials,
} from "./schemas/index.js";
